version: '3.8'  # Docker Compose file format version

services:
  starships:
    # Use a pre-built container image from GitHub Container Registry
    image: ghcr.io/georgiamraz/starships_container:v0.1.2

    # Uncomment this line if you are using a Mac to enforce compatibility
    # platform: linux/amd64

    # Name for the running container (makes it easier to identify)
    container_name: starships_container

    # Set environment variables inside the container
    # USER_ID may be required for file permissions, especially when mounting volumes
    environment:
      - USER_ID="501"

    # Map ports: host:container
    # This makes the Jupyter notebook accessible at http://localhost:8091
    ports:
      - "8091:8091"

    volumes:
      # Don't change this path
      - ./data:/home/jovyan
      
      # Mount directories and files from the host to the container
      # Format: /absolute/path/on/host:/path/inside/container

      # Directory with WASP-127 specific data
      - ./WASP-127data:/home/jovyan/WASP-127data

      # Directory containing model files
      - ./Models:/home/jovyan/Models

      # Directory with Jupyter notebooks
      - ./Notebooks:/home/jovyan/Notebooks

      # Parameter file required by the exofile package (overwrite default inside container)
      - ./param.yaml:/usr/local/lib/python3.10/site-packages/exofile/param.yaml

    # Command to start a Jupyter Notebook server inside the container
    command: jupyter notebook --allow-root --ip=0.0.0.0 --port=8091 --no-browser

