version: '3.8'

services:
  starships:
    image: ghcr.io/georgiamraz/starships_container:v0.1.2
    # image: gmraz/starships
    container_name: starships_container
    # Set the environmental variable to set the user permission
    environment:
      - USER_ID="501"

    ports:
      - "8091:8091" # Map container port 8888 to host port 8888 for jupyter lab
    volumes:

    #please change this path name to your files
      - /Users/ronaldmraz/Desktop/STARSHIPS_workshop:/home/jovyan/data # Local data mapping
      - /Users/ronaldmraz/Desktop/starships_container/starships_container/WASP-127data:/home/jovyan/WASP-127data
      - /Users/ronaldmraz/Desktop/starships_container/starships_container/Models:/home/jovyan/Models
      - /Users/ronaldmraz/Desktop/starships_container/starships_container/Notebooks:/home/jovyan/Notebooks
      - /Users/ronaldmraz/Desktop/starships_container/starships_container/param.yaml:/usr/local/lib/python3.10/site-packages/exofile/param.yaml
    command: jupyter notebook --allow-root  --ip=0.0.0.0 --port=8091 --no-browser