version: '3.8'

services:
  starships:
    # image: ghcr.io/georgiamraz/starships_container:latest
    image: obriens/starships
    container_name: starships_container
    # Set the environmental variable to set the user permission
    environment:
      - USER_ID=1000
      - GROUP_ID=1000

    ports:
      - "8091:8091" # Map container port 8888 to host port 8888 for jupyter lab
    volumes:
      - ./data:/home/jovyan/data # Local data mapping
      - ./data:/home/jovyan/starships_data # Location of the pRT_input_data_path directory
      - ./notebooks:/home/jovyan/notebooks # Location of the analysis notebooks
    
    command: jupyter notebook --allow-root  --ip=0.0.0.0 --port=8091 --no-browser
  

    restart: always
